# Default colors
[colors.primary]
background = '#000000'
foreground = '#b5bdc5'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#fa4d56'
green   = '#42be65'
yellow  = '#c8b670'
blue    = '#5080ff'
magenta = '#a665d0'
cyan    = '#50b0e0'
white   = '#b5bdc5'

# Bright colors
[colors.bright]
black   = '#525252'
red     = '#ff7279'
green   = '#7ac098'
yellow  = '#f8e6a0'
blue    = '#78a9ff'
magenta = '#a3a0d8'
cyan    = '#9ac6e0'
white   = '#e0e0e0'
